name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          npm install
          npm list
        
      - name: Build
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          npm run build --verbose
        env:
          NODE_ENV: production
          CI: false

      - name: List dist directory
        if: always()
        run: ls -la dist || echo "dist directory not found"

      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages 